language: python

install:
  - pip install tox 

env:
  - TOX_ENV=pypy2twisted
  - TOX_ENV=pypy2asyncio

script:
  - which python
  - python --version
  - tox -c autobahn/tox.ini -e $TOX_ENV

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false
